---
# Source: airflow/charts/postgresql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-helm-postgresql
  namespace: "airflow-helm"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.1.9
    app.kubernetes.io/instance: airflow-helm
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: true
# Source: airflow/templates/jobs/create-user-job-serviceaccount.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
###########################################
## Airflow Create User Job ServiceAccount
###########################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-helm-create-user-job
  labels:
    tier: airflow
    component: create-user-job
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
# Source: airflow/templates/jobs/migrate-database-job-serviceaccount.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
#############################################
## Airflow Migrate Database Job ServiceAccount
##############################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-helm-migrate-database-job
  labels:
    tier: airflow
    component: run-airflow-migrations
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
# Source: airflow/templates/redis/redis-serviceaccount.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
######################################
## Airflow Redis ServiceAccount
######################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-helm-redis
  labels:
    tier: airflow
    component: redis
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
# Source: airflow/templates/scheduler/scheduler-serviceaccount.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
################################
## Airflow Scheduler ServiceAccount
#################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-helm-scheduler
  labels:
    tier: airflow
    component: scheduler
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
# Source: airflow/templates/statsd/statsd-serviceaccount.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
######################################
## Airflow StatsD ServiceAccount
######################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-helm-statsd
  labels:
    tier: airflow
    component: statsd
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
# Source: airflow/templates/triggerer/triggerer-serviceaccount.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
################################
## Airflow Triggerer ServiceAccount
#################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-helm-triggerer
  labels:
    tier: airflow
    component: triggerer
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
# Source: airflow/templates/webserver/webserver-serviceaccount.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
######################################
## Airflow Webserver ServiceAccount
######################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-helm-webserver
  labels:
    tier: airflow
    component: webserver
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
# Source: airflow/templates/workers/worker-serviceaccount.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
################################
## Airflow Worker ServiceAccount
#################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-helm-worker
  labels:
    tier: airflow
    component: worker
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
---
# Source: airflow/charts/postgresql/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-helm-postgresql
  namespace: "airflow-helm"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.1.9
    app.kubernetes.io/instance: airflow-helm
    app.kubernetes.io/managed-by: Helm
# yamllint disable rule:indentation
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
# Source: airflow/templates/rbac/pod-launcher-role.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
################################
## Airflow Pod Launcher Role
#################################
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-helm-pod-launcher-role
  namespace: "airflow-helm"
  labels:
    tier: airflow
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "create"
      - "list"
      - "get"
      - "patch"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "create"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "list"
# Source: airflow/templates/rbac/pod-log-reader-role.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
################################
## Airflow Pod Reader Role
#################################
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-helm-pod-log-reader-role
  namespace: "airflow-helm"
  labels:
    tier: airflow
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "get"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
      - "list"
---
# Source: airflow/charts/postgresql/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-helm-postgresql
  namespace: "airflow-helm"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.1.9
    app.kubernetes.io/instance: airflow-helm
    app.kubernetes.io/managed-by: Helm
roleRef:
  kind: Role
  name: airflow-helm-postgresql
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: airflow-helm-postgresql
    namespace: "airflow-helm"
# Source: airflow/templates/rbac/pod-launcher-rolebinding.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
################################
## Airflow Pod Launcher Role Binding
#################################
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: "airflow-helm"
  name: airflow-helm-pod-launcher-rolebinding
  labels:
    tier: airflow
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-helm-pod-launcher-role
subjects:
  - kind: ServiceAccount
    name: airflow-helm-worker
    namespace: "airflow-helm"
# Source: airflow/templates/rbac/pod-log-reader-rolebinding.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
################################
## Airflow Pod Reader Role Binding
#################################
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: "airflow-helm"
  name: airflow-helm-pod-log-reader-rolebinding
  labels:
    tier: airflow
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-helm-pod-log-reader-role
subjects:
  - kind: ServiceAccount
    name: airflow-helm-webserver
    namespace: "airflow-helm"
  - kind: ServiceAccount
    name: airflow-helm-triggerer
    namespace: "airflow-helm"
# Source: airflow/templates/rbac/security-context-constraint-rolebinding.yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
################################
## Airflow SCC Role Binding
#################################
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: "airflow-helm"
  name: airflow-helm-scc-rolebinding
  labels:
    tier: airflow
    release: airflow-helm
    chart: "airflow-1.8.0"
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: airflow-helm-webserver
    namespace: "airflow-helm"
  - kind: ServiceAccount
    name: airflow-helm-worker
    namespace: "airflow-helm"
  - kind: ServiceAccount
    name: airflow-helm-scheduler
    namespace: "airflow-helm"
  - kind: ServiceAccount
    name: airflow-helm-statsd
    namespace: "airflow-helm"
  - kind: ServiceAccount
    name: airflow-helm-triggerer
    namespace: "airflow-helm"
  - kind: ServiceAccount
    name: airflow-helm-migrate-database-job
    namespace: "airflow-helm"
  - kind: ServiceAccount
    name: airflow-helm-create-user-job
    namespace: "airflow-helm"
