# permissions for end users to view airflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: airflow-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: airflow-helm-operator
    app.kubernetes.io/part-of: airflow-helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: airflow-viewer-role
rules:
- apiGroups:
  - workflow.apache.org
  resources:
  - airflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workflow.apache.org
  resources:
  - airflows/status
  verbs:
  - get
