# The official airflow helm chart's redis component does not autogenerate the 
# required rbac for redis to work on openshift ootb so piggy-back on postgres
# role to get anyuid when testing helmchart on openshift
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-helm-redis
  namespace: airflow-helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-helm-postgresql
subjects:
- kind: ServiceAccount
  name: airflow-helm-redis
  namespace: airflow-helm
