apiVersion: workflow.apache.org/v1alpha1
kind: AirFlow
metadata:
  name: airflow-helm
spec:
  webserver:
    replicas: 2
    readinessProbe:
      initialDelaySeconds: 45
    livenessProbe:
      initialDelaySeconds: 60
