# missing redis rolebinding to get anyuid needs to be added manually
rbac:
  createSCCRoleBinding: true
postgresql:
  rbac:
    create: true
    rules:
    - apiGroups: ["security.openshift.io"]
      resources: ["securitycontextconstraints"]
      resourceNames: ["anyuid"]
      verbs: ["use"]
  serviceAccount:
    create: true
