apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: airflow-hybrid-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: experimental airflow operator
  displayName: airflow-hybrid-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - airflow
  - experimental
  links:
  - name: Airflow Hybrid Operator
    url: https://airflow-hybrid-operator.domain
  maintainers:
  - email: skattoju@redhat.com
    name: sid
  maturity: alpha
  provider:
    name: airflow-hybrid-operator
    url: github.com/skattoju/airflow-hybrid-operator
  version: 0.0.0
