apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: airflow-helm-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Deploys Apache Airflow based on the official helm chart with openshift
    specific modifications applied by default
  displayName: Airflow Helm Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - airflow
  - data
  - batch
  - scheduler
  - data workflow
  links:
  - name: Airflow Helm Operator
    url: https://airflow-helm-operator.domain
  maturity: alpha
  provider:
    name: opdev
    url: opdev.github.io
  version: 0.0.0
