apiVersion: workflow.apache.org/v1alpha1
kind: AirFlow
metadata:
  name: airflow-helm
  labels:
    release: airflow-helm
spec:
  webserver:
    serviceAccount:
      create: false
      name: airflow-helm-webserver
    replicas: 2
    readinessProbe:
      initialDelaySeconds: 45
    livenessProbe:
      initialDelaySeconds: 60
